name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
authors:     [RoyCurtis]
website:     https://github.com/Gamealition/SignShopExport
main:        roycurtis.signshopexport.SignShopExport
depend:      [SignShop]