name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
authors:     [RoyCurtis]
website:     https://github.com/Gamealition/SignShopExport
main:        roycurtis.signshopexport.SignShopExport
softdepend:  [SignShop, QuickShop]


commands:
  signshopexport:
    description: Reloads SignShopExport's config and triggers an export
    aliases: [sse]
    permission: signshopexport.reload

permissions:
   signshopexport.reload:
     description: Allows reloading of SignShopExport's config and triggering of export
     default: op